INSERT INTO TBL_PRODUCT (ID, PRICE, PRODUCT_NAME) VALUES (1,10, 'Product 1');
INSERT INTO TBL_PRODUCT (ID, PRICE, PRODUCT_NAME) VALUES (2,20, 'Product 2');
INSERT INTO TBL_PRODUCT (ID, PRICE, PRODUCT_NAME) VALUES (3,30, 'Product 3');